javac -classpath "C:\Program Files\Java\jdk1.8.0_20;C:\Program Files\Java\jdk1.8.0_20\jre\lib\rt.jar;C:\Program Files\Java\jdk1.8.0_20\lib\tools.jar" Generation.java
javac -classpath "C:\Program Files\Java\jdk1.8.0_20;C:\Program Files\Java\jdk1.8.0_20\jre\lib\rt.jar;C:\Program Files\Java\jdk1.8.0_20\lib\tools.jar" Grafi.java
javac -classpath "C:\Program Files\Java\jdk1.8.0_20;C:\Program Files\Java\jdk1.8.0_20\jre\lib\rt.jar;C:\Program Files\Java\jdk1.8.0_20\lib\tools.jar" Session.java
javac -classpath "C:\Program Files\Java\jdk1.8.0_20;C:\Program Files\Java\jdk1.8.0_20\jre\lib\rt.jar;C:\Program Files\Java\jdk1.8.0_20\lib\tools.jar" ParamValue.java
javac -classpath "C:\Program Files\Java\jdk1.8.0_20;C:\Program Files\Java\jdk1.8.0_20\jre\lib\rt.jar;C:\Program Files\Java\jdk1.8.0_20\lib\tools.jar" Parameter.java
javac -classpath "C:\Program Files\Java\jdk1.8.0_20;C:\Program Files\Java\jdk1.8.0_20\jre\lib\rt.jar;C:\Program Files\Java\jdk1.8.0_20\lib\tools.jar" vectTableModel.java
javac -classpath "C:\Program Files\Java\jdk1.8.0_20;C:\Program Files\Java\jdk1.8.0_20\jre\lib\rt.jar;C:\Program Files\Java\jdk1.8.0_20\lib\tools.jar" MainGui.java



